---
title: "SOC4001 Procesamiento avanzado de bases de datos en R"
author: "Tarea 1, respuestas"
format: html
editor: visual
---

```{r, echo=FALSE}
# Escribir install.packages("tinytex") en la consola para instalar "tinytex"
# Carga "tinytex" para compilar PDF
library("tinytex")
```

Ponderación: 12% de la nota final del curso Entrega: Desde el momento de entrega, los estudiantes tiene 1 exacta semana de plazo para completar esta tarea. Formato: Desarrollar esta tarea en un RScript, agregando comentarios cuando sea necesario.

1)  Instalar y cargar el paquete (desde el Script) `CarData`.

2)  Usa la documentación del paquete `CarData` para identificar los datos correspondientes a "Self-Reports of Height and height"

3)  Carga los datos y crea un objeto que los contenga. Llama tal objeto "datos_davis".

4)  Muestra las primeras y las últimas 6 observaciones de la base de datos en la consola.

5)  Crea una base de datos que contenga sólo las variables `sex`, `height` y `repht` de "datos_davis". Llama tal objeto "subdatos_davis". Muestra las dimensiones de la nueva bases de datos.

6)  Presenta un resumen estadístico (summary) de las variables en "subdatos_davis".

7)  Crea una variable llamada "ratio" que mida la razón (división) entre la altura real (`height`) y la altura reportada (`repht`) por los individuos y añadela a "subdatos_davis".

8)  Chequea la presencia de valores perdidos en la variable "ratio". Luego crea una nueva base de datos que contenga sólo las observaciones con datos completos en todas las variables en "subdatos_davis". Llama este objeto "subdatos_davis_full" y presenta un resumen estadístico (summary) de las variables en "subdatos_davis_full".

9)  Crea una nueva variable llamada "sex_num". Asigna valor 1 a "sex_num" para aquellas observaciones en las cuales la variable "sex" toma valor "F" (mujer). Asigna valor 0 a "sex_num" para aquellas observaciones en las cuales la variable "sex" toma un valor "M" (hombre).

10) Usa un loop para calcular la media de la variable "ratio" para las observaciones en cada uno de los niveles de la variable "sex" (es decir, para hombres y mujeres). No olvides usar el comando `print()` para mostrar los cálculos ejecutados dentro del loop.
